---
all:
  children:
    master_host:
      hosts:
        xubuntu: 
          ansible_host: 192.168.126.133

    rabbitmq_group:
      hosts:
        comrade2: 
          ansible_host: 192.168.126.134
          ansible_user: comrade2
        comrade3: 
          ansible_host: 192.168.126.135
          ansible_user: comrade3
        comrade4:
          ansible_host: 192.168.126.136
          ansible_user: comrade4
          
      vars:
        ansible_user: comrade
        ansible_python_interpreter: /usr/bin/python2
